name: dnsjava CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-latest, windows-latest ]
        java: [ '1.8', '11' ]
        arch: [ 'x86', 'x64' ]
        exclude:
          - os: ubuntu-16.04
            arch: x86
          - os: ubuntu-latest
            arch: x86

    name: Java ${{ matrix.java }}/${{ matrix.arch }}/${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Cache Maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.arch }}

      - name: Build with Maven
        run: mvn test jacoco:report -B -"Dgpg.skip"
